# 
# To start the services, run: docker-compose up -d
# To stop the services, run: docker-compose down
#

name: gadget  # Name of Docker group services
services:
  # |**************************************************|
  # |------------------ Server NGINX ------------------|
  nginx-gadget:
    container_name: nginx-gadget
    image: nginx:latest
    volumes:
      - ./config/nginx/conf.d/:/etc/nginx/conf.d
      - ./config/nginx/ssl/:/etc/nginx/ssl
      - ./config/nginx/proxy_params:/etc/nginx/proxy_params
      - ${PROJECT_DIR}:/var/www
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - dev


  # |**************************************************|
  # |------------ Server NodeJS (Frontend) ------------|
  frontend:
    container_name: frontend
    build:
      context: ./config/nodejs
    tty: true
    volumes:
      - ${PROJECT_DIR}:/opt/server
    env_file:
      - .env
    expose:
      - '3000'
    networks:
      - dev


  # |**************************************************|
  # |----------- Server NodeJS (API Backend) ----------|
  backend:
    container_name: backend
    build:
      context: ./config/nodejs
    tty: true
    volumes:
      - ${PROJECT_DIR}:/opt/server
    env_file:
      - .env
    expose:
      - '3000'
    depends_on:
      - postgres-gadget
    networks:
      - dev


  # |**************************************************|
  # |------------ Server DataBase Postgres ------------|
  postgres-gadget:
    container_name: postgres-gadget
    image: postgres:latest
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    networks:
      - dev


  # |**************************************************|
  # |------------ Server DB Management Tool -----------|
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - postgres-gadget
    networks:
      - dev

  # |**************************************************|
  # |------------- Server Minio (AWS S3) --------------|
  minio-gadget:
    image: minio/minio:latest
    container_name: minio-gadget
    command: server /data --console-address ":9001"
    environment:
      # Note: Ensure to set these variables in your .env file
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ./data/minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - dev


  # |**************************************************|
  # |-------------- Server DataBase MySQL -------------|
  # mysql8:
  #   container_name: mysql8
  #   image: mysql:8.0
  #   volumes:
  #     - ./data/mysql8:/var/lib/mysql
  #     - ./config/mysql/8/my.cnf:/root/.my.cnf:ro
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   networks:
  #     - dev

  # |**************************************************|
  # |------------ Server DataBase MongoDB -------------|
  # mongodb:
  #   image: mongo:4.2.3
  #   container_name: mongodb
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: admin
  #   volumes:
  #     - ./data/mongodb:/data/db
  #     - ${PROJECT_DIR}:/www
  #   ports:
  #     - '27017-27019:27017-27019'
  #   networks:
  #     - dev

  # |**************************************************|
  # |------------------ Server Redis ------------------|
  # redis:
  #   image: redis
  #   container_name: redis
  #   volumes:
  #     - ./data/redis:/data
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - dev

  # |**************************************************|
  # |------------------ Server RabbitMQ ---------------|
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
  #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  #   networks:
  #     - dev


  # |**************************************************|
  # |------------------ Server Networks ---------------|
networks:
  dev:
    name: dev
    driver: bridge


# This is a Docker Compose file for setting up a development environment with various services.
# It includes services for NGINX, Node.js frontend and backend, PostgreSQL, Adminer, Minio (AWS S3), and optional services like MySQL, MongoDB, Redis, and RabbitMQ.
# The services are connected to a custom network named 'dev' and use volumes for persistent data storage.
# The environment variables for sensitive data like passwords and user credentials are expected to be defined in a separate .env file. 
# The file is structured to allow easy addition or removal of services as needed for the development workflow.
# Note: Uncomment the MySQL, MongoDB, Redis, and RabbitMQ sections if you need those services.
# Ensure to set the necessary environment variables in your .env file before running the Docker Compose command.
# To start the services, run: docker-compose up -d
# To stop the services, run: docker-compose down
# This file is designed to be used in a development environment and may require adjustments for production use
# Ensure to check the configurations and security settings before deploying in a production environment.